import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';

// The export menu. The structural formats are generated by the server (the same
// pipeline as `manage.py joist_export`), while PNG and SVG stay in the browser,
// so this is where the two halves are seen from the user's side.

test.beforeEach(async ({ page }) => {
  await page.goto('/joist/');
  await expect(page.locator('#joist-canvas svg')).toBeVisible();
  await page.locator('#joist-export-btn').click();
  await expect(page.locator('#joist-popover')).toContainText('Export view');
  // The shared popover is a named dialog, relabelled per content: this is the
  // export menu, so that is what it is called.
  await expect(page.locator('#joist-popover')).toHaveAttribute('aria-label', 'Export view');
});

test('the menu offers both the server formats and the client ones', async ({ page }) => {
  const menu = page.locator('#joist-popover');
  await expect(menu).toContainText('DBML');
  await expect(menu).toContainText('Data dictionary (Markdown)');
  await expect(menu).toContainText('Export SVG');

  // The export route exists in this lane, so the server-backed items are live:
  // without it they are offered disabled rather than throwing on click.
  await expect(menu.locator('[data-act="dbml"]')).toBeEnabled();
  await expect(menu.locator('[data-act="md"]')).toBeEnabled();
  await expect(menu.locator('[data-act="png"]')).toBeEnabled();
  await expect(menu.locator('[data-act="svg"]')).toBeEnabled();
});

test('the menu opens and closes from the keyboard', async ({ page }) => {
  await page.keyboard.press('Escape');
  await expect(page.locator('#joist-popover')).toBeHidden();

  await page.locator('#joist-export-btn').focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('#joist-popover')).toBeVisible();

  await page.keyboard.press('Escape');
  await expect(page.locator('#joist-popover')).toBeHidden();
});

test('downloading DBML returns what the server generated', async ({ page }) => {
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.locator('#joist-popover [data-act="dbml"]').click(),
  ]);

  expect(download.suggestedFilename()).toMatch(/\.dbml$/);
  const body = readFileSync(await download.path(), 'utf8');
  expect(body).toContain('Table testapp_book');
  expect(body).toContain('Table testapp_author');
});

test('downloading the SVG returns the diagram the browser drew', async ({ page }) => {
  const [download] = await Promise.all([
    page.waitForEvent('download'),
    page.locator('#joist-popover [data-act="svg"]').click(),
  ]);

  expect(download.suggestedFilename()).toMatch(/\.svg$/);
  const body = readFileSync(await download.path(), 'utf8');
  expect(body).toContain('<svg');
  // The accessibility output survives the export: an SVG that announces nothing
  // is a picture of a schema rather than a schema.
  expect(body).toContain('Database structure diagram');
});
