# Generated by Django 6.1.1 on 2026-09-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('pick', 'Pick'), ('adjustment', 'Adjustment'), ('return', 'Return')], max_length=16)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.PositiveIntegerField(default=0)),
                ('max_quantity', models.PositiveIntegerField(default=0)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('warehouse', 'variant'), name='uq_stock_warehouse_variant'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='ck_stock_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='reorderrule',
            constraint=models.UniqueConstraint(fields=('variant', 'warehouse'), name='uq_reorder_variant_wh'),
        ),
    ]
