"""Raw-SQL structure the model-based fixtures cannot express, one variant per
backend: an explicit database-level foreign key action (Django's ``on_delete``
is application-level and never reaches the DDL), a composite primary key, a
table with no primary key at all, and comments (PostgreSQL and MySQL only).

Written as plain DDL on purpose. Django's schema editor does not emit
``DEFAULT``, ``COMMENT`` or ``ON DELETE`` clauses for migration-created tables,
so a table built the normal way cannot carry them and the introspection paths
that read them would stay unverified.

SQLite gets the same tables minus the comments, so the shape assertions hold on
every backend while the comment assertions are native-lane only.
"""

from django.db import migrations

TABLES = ("testapp_fkaction", "testapp_compositepk", "testapp_nopk", "testapp_noted")

DDL = {
    "postgresql": [
        """
        CREATE TABLE "testapp_fkaction" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "author_id" bigint NOT NULL,
            CONSTRAINT "testapp_fkaction_author_id_fk" FOREIGN KEY ("author_id")
                REFERENCES "testapp_author" ("id") ON DELETE CASCADE ON UPDATE RESTRICT
        )
        """,
        """
        CREATE TABLE "testapp_compositepk" (
            "a" integer NOT NULL,
            "b" integer NOT NULL,
            "note" varchar(50) NOT NULL DEFAULT 'n/a',
            PRIMARY KEY ("a", "b")
        )
        """,
        """
        CREATE TABLE "testapp_nopk" (
            "label" varchar(50),
            "qty" integer NOT NULL DEFAULT 7
        )
        """,
        """
        CREATE TABLE "testapp_noted" (
            "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "label" varchar(50)
        )
        """,
        "COMMENT ON TABLE \"testapp_noted\" IS 'Every noted thing'",
        "COMMENT ON COLUMN \"testapp_noted\".\"label\" IS 'Human label'",
    ],
    "mysql": [
        """
        CREATE TABLE `testapp_fkaction` (
            `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
            `author_id` bigint NOT NULL,
            CONSTRAINT `testapp_fkaction_author_id_fk` FOREIGN KEY (`author_id`)
                REFERENCES `testapp_author` (`id`) ON DELETE CASCADE ON UPDATE RESTRICT
        )
        """,
        """
        CREATE TABLE `testapp_compositepk` (
            `a` integer NOT NULL,
            `b` integer NOT NULL,
            `note` varchar(50) NOT NULL DEFAULT 'n/a',
            PRIMARY KEY (`a`, `b`)
        )
        """,
        """
        CREATE TABLE `testapp_nopk` (
            `label` varchar(50),
            `qty` integer NOT NULL DEFAULT 7
        )
        """,
        """
        CREATE TABLE `testapp_noted` (
            `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
            `label` varchar(50) COMMENT 'Human label'
        ) COMMENT='Every noted thing'
        """,
    ],
    "sqlite": [
        # SQLite has no COMMENT and no ALTER TABLE ... ADD CONSTRAINT, but it
        # does declare referential actions and defaults inline.
        """
        CREATE TABLE "testapp_fkaction" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "author_id" bigint NOT NULL REFERENCES "testapp_author" ("id")
                ON DELETE CASCADE ON UPDATE RESTRICT
        )
        """,
        """
        CREATE TABLE "testapp_compositepk" (
            "a" integer NOT NULL,
            "b" integer NOT NULL,
            "note" varchar(50) NOT NULL DEFAULT 'n/a',
            PRIMARY KEY ("a", "b")
        )
        """,
        """
        CREATE TABLE "testapp_nopk" (
            "label" varchar(50),
            "qty" integer NOT NULL DEFAULT 7
        )
        """,
        """
        CREATE TABLE "testapp_noted" (
            "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
            "label" varchar(50)
        )
        """,
    ],
}


def create_fixtures(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor not in DDL:
        raise RuntimeError(f"no test fixtures are written for the {vendor!r} backend")
    for statement in DDL[vendor]:
        schema_editor.execute(statement)


def drop_fixtures(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor not in DDL:
        raise RuntimeError(f"no test fixtures are written for the {vendor!r} backend")
    for table in TABLES:
        schema_editor.execute(f"DROP TABLE {schema_editor.quote_name(table)}")


class Migration(migrations.Migration):
    dependencies = [("testapp", "0001_initial")]

    # Raw DDL: MySQL cannot roll these back inside a transaction anyway.
    atomic = False

    operations = [migrations.RunPython(create_fixtures, drop_fixtures)]
