# Generated by Django 6.1.1 on 2026-09-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='catalog_product_status_idx',
        ),
    ]
